### ISSUE TITLE
`node:` imports aren't supported in Node.js v14

### ISSUE THREAD

**Issue by electerious** [sindresorhus/eslint-plugin-unicorn#1867]
The [rule.js](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/rules/utils/rule.js#L2-L3) file uses `node:` imports which are supported since Node.js v16, but `eslint-plugin-unicorn` says it supports v14 and up.

The original error message:

```
Error: Failed to load plugin 'unicorn' declared in '.eslintrc.json': Cannot find module 'node:path'
Require stack:
- eslint-plugin-unicorn@43.0.2_eslint@8.20.0/node_modules/eslint-plugin-unicorn/rules/utils/rule.js
- eslint-plugin-unicorn@43.0.2_eslint@8.20.0/node_modules/eslint-plugin-unicorn/index.js
- @eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
```

The issue occurs after upgrading from 42.0.0 to 43.0.2.

It's a bit confusing that the tests are passing despite that they're running with v14, too.

**Comment by electerious** [comment]
My fault. `node:` is supported since v14.13.1, but my version was slightly below.

**Comment by axelboc** [comment]
I've just hit this. Seems that Node 14.13.1+ only supports `node:*` imports from ESM files -- not from CJS files. I found the info here: https://github.com/gregnb/filemanager-webpack-plugin/issues/101#issuecomment-867859903.

I recommend re-opening this issue and either increasing the minimum Node version to v16, reverting to unprefixed paths, or making sure the `node:` prefixes are removed in the CJS output.

**Comment by axelboc** [comment]
Okay, got it: they've added support for `node:*` imports from CJS in Node 14.18.0: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V14.md#2021-09-28-version-14180-fermium-lts-targos

So bumping the minimum Node version to v14.18.0 should do the trick.

**Comment by bmish** [comment]
We could mention the Node version support in the rule doc to reduce confusion here: https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1874
