### ISSUE TITLE
Cannot find module 'eslint/use-at-your-own-risk' with ESLint v7

### ISSUE THREAD

**Issue by EvgenyOrekhov** [sindresorhus/eslint-plugin-unicorn#1544]
Can't use eslint-plugin-unicorn v37.0.0 with ESLint 7.32.0.

ESLint gives the following fatal error:

```text
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load plugin 'unicorn' declared in '.eslintrc.json': Cannot find module 'eslint/use-at-your-own-risk'
Require stack:
- /example/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js
- /example/node_modules/eslint-plugin-unicorn/rules/utils/rule.js
- /example/node_modules/eslint-plugin-unicorn/index.js
- /example/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /example/node_modules/@eslint/eslintrc/lib/index.js
- /example/node_modules/eslint/lib/cli-engine/cli-engine.js
- /example/node_modules/eslint/lib/eslint/eslint.js
- /example/node_modules/eslint/lib/eslint/index.js
- /example/node_modules/eslint/lib/cli.js
- /example/node_modules/eslint/bin/eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/example/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/example/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:5:18)
    at Module._compile (/example/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

eslint-plugin-unicorn v36.0.0 works fine with ESLint 7.32.0

**Comment by zilahir** [comment]
this issue still persists with eslint version 7.32.0: 

```
Failed to load plugin 'eslint-plugin-unicorn' declared in '.eslintrc': Cannot find module 'eslint/use-at-your-own-risk'
```

with 

```
eslint-plugin-unicorn@41.0.1
```

**Comment by ilumin** [comment]
This issue was gone with `eslint@8.26.0`

**Comment by iamgodpyx** [comment]
@typescript-eslint/eslint-plugin@8.19.1
