### PR TITLE
Mention Node version support in `prefer-node-protocol` rule

### LINKED ISSUE #1867: `node:` imports aren't supported in Node.js v14
The [rule.js](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/rules/utils/rule.js#L2-L3) file uses `node:` imports which are supported since Node.js v16, but `eslint-plugin-unicorn` says it supports v14 and up.

The original error message:

```
Error: Failed to load plugin 'unicorn' declared in '.eslintrc.json': Cannot find module 'node:path'
Require stack:
- eslint-plugin-unicorn@43.0.2_eslint@8.20.0/node_modules/eslint-plugin-unicorn/rules/utils/rule.js
- eslint-plugin-unicorn@43.0.2_eslint@8.20.0/node_modules/eslint-plugin-unicorn/index.js
- @eslint+eslintrc@1.3.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
```

The issue occurs after upgrading from 42.0.0 to 43.0.2.

It's a bit confusing that the tests are passing despite that they're running with v14, too.

### PR DESCRIPTION
**Pull request by bmish**
Document the supported Node versions for the node protocol import feature to reduce potential confusion or mistaken adoption of this lint rule.

While eslint-plugin-unicorn only supports Node 14.18 and above:

https://github.com/sindresorhus/eslint-plugin-unicorn/blob/20e959ffadeca007697534f1ad58c45d29cfdb04/package.json#L14

Some libraries that intend to support all versions of Node 14 might accidentally adopt this lint rule since it's very common to only test against the latest Node 14 and not necessarily against early versions of it.

Fixes #1867.

### CODE REVIEW

File: docs/rules/prefer-node-protocol.md [hunk 1]
```diff
@@ -11,6 +11,12 @@ When importing builtin modules, it's better to use the [`node:` protocol](https:
 
 And don't forget to [upvote this issue](https://github.com/nodejs/node/issues/38343) if you agree.
 
+Note that this feature is not available in early versions of Node 12 and Node 14:
+
+> v16.0.0, v14.18.0 (ESM import and CommonJS require())
```
Comment (ddzz) [inline docs/rules/prefer-node-protocol.md:16]: Why not mention Node 18 here as well?

Comment (bmish) [reply docs/rules/prefer-node-protocol.md:16]: This text was copied directly from https://nodejs.org/api/esm.html#node-imports and is only supposed to mention the initial Node versions that supported this feature. Since Node 16 has full support for it, any subsequent versions can be assumed to fully support it as well.

Comment (sindresorhus) [inline docs/rules/prefer-node-protocol.md:16]: This is correct for `require` but not for ESM.

Comment (sindresorhus) [inline docs/rules/prefer-node-protocol.md:16]:
```suggestion
> v16.0.0, v14.18.0 (CommonJS `require()`)
```

Not clear to me why this is mentioning ESM.

File: docs/rules/prefer-node-protocol.md [hunk 2]
```diff
@@ -11,6 +11,12 @@ When importing builtin modules, it's better to use the [`node:` protocol](https:
 
 And don't forget to [upvote this issue](https://github.com/nodejs/node/issues/38343) if you agree.
 
+Note that this feature is not available in early versions of Node 12 and Node 14:
```
Comment (sindresorhus) [inline docs/rules/prefer-node-protocol.md:14]: I don't think we need to mention Node.js 12 as it's not supported anymore.

**Comment by sindresorhus** [comment]
Bump

File: docs/rules/prefer-node-protocol.md (hunk 1 above)
Comment (bmish) [reply docs/rules/prefer-node-protocol.md]: Removed unnecessary mentions of ESM/CJS.

File: docs/rules/prefer-node-protocol.md (hunk 2 above)
Comment (bmish) [reply docs/rules/prefer-node-protocol.md]: I removed "Node 12" from this sentence. However, I do think we should continue to mention it in the versions list below for completeness / to accurately satisfy the wording "Node.js support for this feature began in". Once all of eslint-plugin-unicorn's Node versions support this feature, I think we can just remove this section completely.

**Comment by bmish** [comment]
Sorry for the delay. Should be ready if still interested.
